sandstorm-io/vagrant-spk

vagrant-spk
This PR is blocked on https://github.com/sandstorm-io/sandstorm/pull/494 making it into a sandstorm binary release; don't merge until that one is released.
-----
A PR for spk prevents us from hitting the 4096-file-handle limit:
https://github.com/sandstorm-io/sandstorm/pull/494
So we can switch back to the default shared folder mechanism, which
has a couple of nice benefits:
1. Works on Windows at all
2. OSX users don't have to enter sudo password every time they start or stop
the VM
3. Can map /vagrant to the same folder as /opt/app
Libvirt still does better with an explicit p9fs, which is bidirectional, as
opposed to the default synced_folder backend, which is rsync and only syncs
from host to guest.
=> Vagrantfile: switch back to vboxsf

vagrant-spk
This is theoretically safer than hard-coding `/usr/bin/python2.7`.
Hat-tip to @alex for suggesting this.
=> Use $PATH to find python2.7

vagrant-spk
This brings disk usage down to ~15MB.  I don't think we'll be able to do much
better; InnoDB requires at least 10MB for its data file path, so short of using
a patched mysqld, we can't fix this.
We could consider maintaining a patched MySQL which gets automatically pulled
in for vagrant-spk users, if that seems like a worthwhile time investment.
Worth noting: this is likely *not* a safe thing to push to existing packages with MySQL DBs.
https://dev.mysql.com/doc/refman/5.5/en/innodb-data-log-reconfiguration.html
suggests that you'd have to tell the server to completely flush the log, then
manually delete the logfiles before changing their size in the config.
=> Reduce MySQL disk usage

vagrant-spk
This commit fixes an issue where the [mysqld] string is placed
before the heredoc that uses it.
Thanks to Jack Singleton for finding it.
=> Fix command-not-found issue in setup.sh for Python stack

vagrant-spk
On Windows, there's a path limit that Meteor/npm frequently exceed.  When we
attempt to build a bundle under /opt/app/.sandstorm/, it fails because Windows
will not allow such a long path.
This patchset makes vagrant-spk build the app in the guest OS in the vagrant
user's homedir instead.
=> Make meteor build the bundle on the guest fs

windows-support/Makefile
Now you can theoretically just run "make" and get the packaged exe, rather than having to click through some setup wizards.
@paulproteus review and merge?
=> Headless, full-auto, DRY win32 package building

stacks/diy/build.sh, stacks/diy/launcher.sh, stacks/diy/setup.sh, stacks/lemp/build.sh, stacks/lemp/launcher.sh, stacks/lemp/setup.sh, stacks/meteor/build.sh, stacks/meteor/initargs, stacks/meteor/launcher.sh, stacks/meteor/setup.sh, stacks/static/launcher.sh, stacks/static/setup.sh, stacks/uwsgi/build.sh, stacks/uwsgi/launcher.sh, stacks/uwsgi/setup.sh, vagrant-spk, windows-support/windows-installer.iss
This should make it easier to edit, discover, and iterate on scripts.
While I was moving all the scripts, I made them all run
`set -euo pipefail` as their first action.
Tagging @paulproteus for review, if he likes.
=> Move stack scripts out into folders

vagrant-spk
This will cause redownload rather than failure if a download fails partway
through.
Fixes #60.
=> Atomically commit bundle to ~/.sandstorm/caches/

vagrant-spk
I couldn't think of a better way than to "copy" the spk, since it can be
anywhere on the host filesystem.
=> Add the "publish" command

vagrant-spk
This should improve the experience on Win7 and higher hosts, which will now
assign all the host CPUs and a quarter of the host's RAM (or 512MB, whichever
is larger) to the VM.
=> Windows: detect and use appropriate CPUs/RAM like OSX/Linux

stacks/lemp/setup.sh, stacks/static/setup.sh, stacks/uwsgi/setup.sh
nginx will limit this to 1MB by default, which is pretty small for a lot of
apps that allow e.g. photo or media uploads.
=> nginx: by default, don't limit max body size

stacks/lemp/setup.sh
This allows us to set SANDSTORM=1 in the default environment block generated by
`spk init` and then call getenv("SANDSTORM") in PHP apps to see if they're
being run under Sandstorm or not.
=> lemp: pass environment variables on to php-fpm

vagrant-spk
After #77, on an initial `vagrant-spk up` Sandstorm does not become available on local.sandstorm.io:6080. This patch fixes the problem.
=> Need to restart so the new BIND_IP takes effect.

vagrant-spk
I have tested that this works properly on the Meteor clock. For now, my
main target user is @neynah -- my goal is to set up a process where she
builds sample versions of packages for people so they understand how
cool it would be if they created a "real" package.
Therefore @zarvox I am hopeful that we can have lower code quality behind
the VAGRANT_SPK_EXPERIMENTAL flag. I promise not to change how existing,
non-experimental things work via changes that are only available in
EXPERIMENTAL mode.
FWIW, in the near/long run, this auto mode might be a good idea for real
Sandstorm app authors. I know I would use it, and I actually understand
Sandstorm.
=> Add an experimental auto-packaging command

stacks/meteor/setup.sh
Fixes a bug in migrations.  We should notify app authors to bump their versions
and `vagrant-spk destroy` and `vagrant-spk up` before their next release.
=> meteor stack: bump meteor-spk version to 0.1.8

stacks/meteor/setup.sh, vagrant-spk
This applies mostly to the Meteor stack but also covers downloading
Sandstorm for all stacks.
Addresses feedback from zarvox on #74
=> Print explanations for slow commands we are running

vagrant-spk
I've tested this locally against the Meteor app packaging tutorial. It manages to do:
- vagrant-spk up
- vagrant-spk dev
- vagrant-spk pack (and I even uploaded & manually tested the outputted SPK)
So I think it works. @zarvox please review/merge.
=> Switch to Sandstorm snapshots of debian/jessie64, for vboxsf support

stacks/lemp/setup.sh
Fixes #111
Thanks @ndarilek for finding this and filing it.
=> Use semicolon as PHP config comment marker

vagrant-spk
Also run `spk verify --details` when calling `spk pack` since users are almost
invariably going to want to see that output to sanity-check their metadata.
@paulproteus can I talk you into writing the appropriate docs for this? :)
=> Add "verify" subcommand.

stacks/node/build.sh, stacks/node/launcher.sh, stacks/node/setup.sh
Unfortunately there's not one single standardized way to deploy node apps, so this stack attempts to use the minimal reasonable defaults to get someone up and running with a node app:
* Installs the latest stable node.js (4.x)
* `npm install` and `npm start`
I think it could probably be argued that it's too minimal and the diy stack suffices. The main value is really just using nodesource to get a reasonably up to date node in the VM.
=> Add node stack

stacks/lemp/setup.sh, stacks/static/setup.sh, stacks/uwsgi/setup.sh
This avoids a problem where HTTP 4xx and 5xx error messages are corrupted
in transit to the browser.
Close #33
=> Set "gzip off;" for nginx

stacks/uwsgi/setup.sh
Pip packages can reference git remotes, which is actually done a decent bit in
the Python community.  This should help things be more likely to work out of
the box, and git doesn't pull in too many dependencies, so it shouldn't be too
painful for users that don't need it.
Closes #119
=> Install git by default in uwsgi stack

vagrant-spk
Libvirt refuses to mount two guest folders from the same host folder.  Since we
don't use `/vagrant` anywhere at all; preferring `/opt/app`, we can just
canonicalize on `/opt/app` and disable `/vagrant` entirely.
=> Disable mounting of /vagrant

stacks/lemp/launcher.sh, stacks/lemp/service-config/mime.types, stacks/lemp/service-config/nginx.conf, stacks/lemp/setup.sh, stacks/static/launcher.sh, stacks/static/service-config/mime.types, stacks/static/service-config/nginx.conf, stacks/static/setup.sh, stacks/uwsgi/launcher.sh, stacks/uwsgi/service-config/mime.types, stacks/uwsgi/service-config/nginx.conf, stacks/uwsgi/setup.sh, vagrant-spk
`vagrant-spk setupvm <stack>` will now recursively copy that stack's `service-config` to `$PWD/.sandstorm/service-config`.
Then, we migrate the `static`, `lemp`, and `uwsgi` stacks to use this new functionality for their nginx confs, rather than doing messy patches atop Debian's default configs.
Tested successfully against:
* a minimal `static` stack "app" that just serves an `index.html`
* https://github.com/paulproteus/php-app-to-package-for-sandstorm
* https://github.com/zarvox/python-app-to-package-for-sandstorm
Closes #116.
=> Add `service-config` for stacks and use in static, lemp, and uwsgi stacks

vagrant-spk
Note that this is useless cruft if you are not using git. However, IMHO enough
projects use git such that it is worth adding this without bothering to detect
if this project uses git.
Close #30
(but close #30 in a very minimalist way)
=> Create a .gitignore file by default

stacks/diy/setup.sh, stacks/lemp/setup.sh, stacks/lesp/setup.sh, stacks/meteor/setup.sh, stacks/node/setup.sh, stacks/static/setup.sh, stacks/uwsgi/setup.sh
Rationale:
- @grantpotter emailed me to ask why his vagrant-spk box wasn't being modified
in accordance with his changes to setup.sh. I believe he didn't understand the
comment text in the existing setup.sh because he doesn't have a clear concept
of the boundary between vagrant and vagrant-spk.
- Therefore, I think he would have benefited from a more intense warning plus a
link to the docs.
=> setup.sh: Provide a more intense warning & docs link

vagrant-spk
These are needed for the signing key migration instructions.
=> Add support for `spk keygen` and `spk getkey` commands

vagrant-spk
Close #55
Testing done:
- Run `vagrant-spk setupvm`
- Notice that a `.gitattributes` file indeed got created
- Ran git command to verify attributes.
```
➜  php-app-to-package-for-sandstorm git:(master) git check-attr -a .sandstorm/*.sh
.sandstorm/build.sh: text: set
.sandstorm/build.sh: eol: lf
.sandstorm/global-setup.sh: text: set
.sandstorm/global-setup.sh: eol: lf
.sandstorm/launcher.sh: text: set
.sandstorm/launcher.sh: eol: lf
.sandstorm/setup.sh: text: set
.sandstorm/setup.sh: eol: lf
```
Given that, I think this is OK to merge as-is. @zarvox requesting your +1/-1 on this.
@mautic thanks for your patience with us as we took a while to resolve this.
=> Insist that *.sh files are LF not CRLF

vagrant-spk
As observed by `synchrone` on IRC.
=> vagrant-spk: publish shouldn't crash if user gives no .spk arg

vagrant-spk
=> vagrant-spk: setupvm with no args should list supported stacks

vagrant-spk
In an attempt to clean up the command surface of vagrant-spk, all commands
intended to forward directly to vagrant are now placed under the "vm"
subcommand.
The "up", "ssh", "destroy", "global-status", and "reload" commands are
deprecated in favor of the "vm <subcommand>" equivalents, but will continue to
work with a warning until some future release.
This change also means we can reasonably pass through *any* arguments passed to
`vagrant-spk vm` on to `vagrant`, so we're no longer in the business of
whitelisting arguments and reimplementing all the commands that `vagrant`
provides that people might want to use.
=> Move all vagrant passthrough subcommands under the "vm" subcommand

HOWTO-libvirt.md
This adds some instructions for how to set up `vagrant-spk` with the `libvirt` backend on Linux, rather than the VirtualBox one.  In particular, these instructions focus on Fedora, since that's what the author uses.
@dwrensha thanks for testing these out - let me know if you have any other changes/enhancements you'd suggest!
=> Add instructions for using vagrant-spk with libvirt

HOWTO-libvirt.md
`libvirtd` is nonexistent, so I assume it's this. Will self-merge because we decided these docs need little review, but post-merge review very much welcome.
=> libvirt HOWTO: Debian calls it libvirt-bin

vagrant-spk
The pyinstaller bundle generates a program for which `sys.argv[0]` is not the
full path to the executable, but just the short name of the program.
In this case, we should use `sys.executable` to determine the path to the .exe
that is actually launching vagrant-spk, since that's where the stacks will be
located.
@paulproteus this fixes the issue hexx from IRC was having; if I can impose upon you to put together a Windows release, that'd be cool.
=> Fix executable path detection on Windows 10.

vagrant-spk
Close: #158 
This changeset:
- Adjusts the default `global-setup.sh` so that the two `curl` calls that currently only print error messages now print them error messages through a pipe to cat.
- This has the effect of buffering them, which helps vagrant receive the error messages all at once, in my manual testing.
- Assuming this is implemented correctly, this retains all the same information as before. Any error messages that we were printing before, we are still printing. I know that @zarvox is interested in making sure that we retain the existing discoverability and comprehensibility of `vagrant-spk`.
Here is my proof that the very subtle change on the first line is a safe change to make.
```
paulproteus@slittingmill:~$ cat << EOF > /tmp/print-to-both.sh
> #!/bin/bash
> echo stdout
> …
```
=> For some calls to curl, buffer output via pipe to cat

vagrant-spk
This corrects the deprecation warning so that the suggested command runs without failure, at least on Vagrant 1.8.1
=> fix deprecation warning

README.md
`vagrant-spk up` is deprecated `vagrant-spk vm up` should be used instead
=> Update example usage

windows-support/Makefile, windows-support/windows-installer.iss
Also pin to version 3.1.1 of pyinstaller, which manages to build our program OK.
=> Add helpers to Windows build

helpers/Makefile, helpers/enter-grain-source/Cargo.toml, helpers/enter-grain-source/src/main.rs
With this change, we:
* enable link-time optimization
* use the system allocator over jemalloc
* strip the binary to remove debugging symbols
This reduces the binary size from 644k to 131k.
@paulproteus I didn't update the checked-in `enter_grain` binary or shasum; let me know if you'd like me to do so.  Tragically, any changes we make just make the git tree larger, so I'm not sure checking in non-bugfixes for the binaries is actually a net win.
=> Reduce the size of `enter_grain` by 80%

vagrant-spk
On my Windows10 machine, running vagrant-spk vm up results in a stack trace. This is because I can't bind to 0.0.0.0.
Instead, forcably set it to bind to 127.0.0.1 - all the functionality, none of the issues (for me, at least!)
=> Update Vagrant-SPK to support Windows10 hosts

vagrant-spk
Per the message, these were set to expire August 1, 2016. It's been the
better part of a year since then, so let's kill them already.
=> Remove deprecated commands

vagrant-spk
Typically the command itself prints something reasonable, but we weren't
catching the exception, so this was obscured by a useless python stack
trace. We now catch the exception and print a concise message.
=> Better error messages when a command fails.

vagrant-spk
Context: https://github.com/pgrm/swagger-editor-sandstorm/issues/4
=> Do not rely on launcher.sh being executable

vagrant-spk
The sandstorm/debian-jessie64 VM Box is no longer available for download.
Switched to an alternative box debian/contrib-jessie64.
The new box does not come with curl by default, so the installation line of curl was also added.
=> Updated the box to debian/contrib-jessie64

stacks/lemp/launcher.sh, stacks/lemp/setup.sh
So Debian Stretch installs MariaDB instead of MySQL. That breaks vagrant-spk, so for now, this adds repo.mysql.com as an apt source and gets MySQL proper. MySQL expected an additional directory in var (seems to to `secure_file_priv`), and indicated that the old way of initalizing the database was deprecated, so we're going to try changing that too.
Additionally, this fixes PHP 7's sock file location as with the update-lesp patch.
Fixes #220.
=> Fix LEMP stack, install MySQL

windows-support/windows-installer.iss
Set for next Sandstorm release version (somewhat optimistically). But either way it'll be more accurate than a date in 2015, and give some clear indication if a user has installed a modern vagrant-spk.
Fixes #208.
=> Update version number in Windows installer

vagrant-spk
Fixes #180 in a way that Stack Overflow say is fairly standard. I've had issues in the past with multiple vagrant-spks on a box and not knowing which I just ran, so I personally would find this quite helpful.
In a future world, I'd perhaps like the release.sh script to edit this value (and the similar one in #223) and make a commit. But vagrant-spk releases are fairly infrequent, so my hope is this is adequate enough for now.
=> Add vagrant-spk --version

stacks/uwsgi/launcher.sh, stacks/uwsgi/setup.sh
This PR isn't complete yet, but is currently "better than what currently happens". It updates the MySQL install behavior from my PHP PR (#222), so that we don't install MariaDB.
Current issue using python test app:
> /opt/app/env exists, moving on
/opt/app/.sandstorm/build.sh: line 11: /opt/app/env/bin/pip: No such file or directory
Connection to 127.0.0.1 closed.
[31mCommand failed with a non-zero exit status (127).[0m
I suspect pip needs to be installed somehow, as it is indeed not in /opt/app/env/bin.
=> Update uwsgi stack for Stretch

README.md
The old URL still redirects, but I like tidiness.
=> Readme: Correct URL for moved repo

stacks/meteor/build.sh, stacks/meteor/setup.sh
Heavily based on @aruntk's work (see https://github.com/CommonGarden/Grow-IoT/commit/3f10818a3fa861127f113711099914c7157c7e47), I am trying to mark him as a co-author on the commit.
Fixes #152 and fixes #193 (and several issues on other repositories).
=> Update Meteor stack to 1.6.1.1

vagrant-spk
Fixes #235.
This significantly improves the access to this command by replacing
`vagrant-spk vm ssh`
`spk listkeys -k ~/.sandstorm/sandstorm-keyring`
with
`vagrant-spk listkeys`
=> Add listkeys command

stacks/uwsgi/launcher.sh
To match lemp stack, and with this change, the python test app works. No idea why I was having difficulty before, because this wasn't the only thing missing.
=> UWSGI: Missing directory in launcher.sh

stacks/golang/setup.sh
Fixes #232. (I think)
Can confirm this change causes it to install golang-1.10, but don't have anything to test against handy.
=> Update Go stack

CHANGELOG.md, vagrant-spk, windows-support/windows-installer.iss
This includes the changelog for everything since 0.230.
=> Bump versions for 0.236 release

vagrant-spk
Housing it in /tmp, which is a tmpfs, runs afoul of this kernel bug:
https://bugzilla.kernel.org/show_bug.cgi?id=183461
Fixes #213 .
=> Move temporary in-vm vagrant-spk dir to  /var/tmp

vagrant-spk
Effectively drops support for Windows XP/Vista from vagrant-spk, but fixes an issue where broken code here does not error out and simply fails silently.
=> Remove rescue block from Windows RAM calculation

README.md, vagrant-spk
We set both the VM to forward port 6090 outside the grain and have Sandstorm install using port 6090 instead of it's default port. All of vagrant-spk's docs will need to be updated by a docs PR before this is merged. I tested this on a Windows machine and installed and used a grain all through port 6090.
=> Switch vagrant-spk to use port 6090

vagrant-spk
Fixes #245 
Super simple for now. It grabs the same code as setupvm but just for Vagrantfile and global-setup.sh, which shouldn't generally be modified by app packagers.
As a test, I grabbed the GitWeb source prior to @abliss updates, because I knew he hit the 404 box issue. Went through the flow and failed to start the VM. I ran `vagrant-spk upgradevm` and then I was able to start up the VM. (Although I also got a 502 Bad Gateway because there was other related bitrot for GitWeb.)
Note that currently neither `setupvm` nor `upgradevm` has any sort of protection to prevent you from clobbering what you have. (This is worse in setupvm's case, because it can mess up your app build.) Though hopefully people are committing to GitHub or have original sources to fall back on. But we can do better …
=> Add upgradevm command

release.sh
I mostly stripped out the logic for determining the version, and added the variables for SemVer. For most intents and purposes, I am looking at major.minor, but I have added the ability to set a patch as necessary, upon which it will show the patch number.
=> Set release.sh to version 1.0 manually

vagrant-spk
Add a link to the server launched on when using the command "vagrant-spk vm up." This makes it easier to launch Sandstorm in the browser without rechecking the documentation.
=> Add server link

vagrant-spk
Fixes #248 
I tested this with diy stack and the VM came up alright. I'll probably do a wholesome test with the Python test app before I merge it. I found grub-pc held up apt-get upgrade, and from a Sandstorm package building standpoint, we hardly care if grub is up to date on the VM, so I held it.
Note that we should document `vagrant-spk vm box update` somewhere for people who currently use vagrant-spk and have the old box downloaded already. But realistically this change should mostly update your box up to the same level anyways.
=> Unpin box and apt upgrade

stacks/golang/build.sh, stacks/golang/setup.sh
Uses the latest version of the toolchain, and supports (only) Go
modules.
=> Update the 'golang' stack.

vagrant-spk
I've tested this change on ShareLatex on my Windows machine: It does indeed cause the vagrant-spk VM to use the correct config option. I placed it by another sandstorm.conf modification just prior to restarting the Sandstorm service, which seemed like a good spot.
This is to ensure new apps and app updates can easily be tested against sandstorm-io/sandstorm#3409. Track our progress on concluding this project at sandstorm-io/sandstorm#3424
vagrant-spk users should be using the latest commit of vagrant-spk, and may need to `vagrant-spk vm destroy`, `vagrant-spk upgradevm`, and then `vagrant-spk vm up` to take advantage of this for existing dev environments.
=> Make vagrant-spk use new CSP when creating VMs

stacks/golang/setup.sh
Upstream just pushed out a patch release today, which fixes a security
vulnerability (I do not believe it affects anything that currently runs
in sandstorm).
=> Bump the golang stack's version number.

stacks/golang/setup.sh
This release includes security fixes for a number of standard library
functions which previously would panic under various circumstances,
potentially allowing denial-of-service attacks.
=> Bump golang stack version.

stacks/golang/setup.sh
Security fix (arbitrary code execution at build-time) -- though the Go
devs are in the minority in even considering that a vulnerability; most
package managers allow this as a fundamental architectural choice :/
=> Bump golang version.

vagrant-spk
This converts the str into bytes, which makes Python 3.8 happy.  Python 2.7 works before and after the change.
=> Fix the setupvm command on Python 3.8

stacks/golang/setup.sh
This is a feature release; it includes changes to standard library and
tooling, though they are backwards compatible, so we still only need
to bump the version number.
=> Golang stack: bump toolchain version.

stacks/lemp/launcher.sh, stacks/lemp/service-config/nginx.conf, stacks/lemp/setup.sh, stacks/lesp/launcher.sh, stacks/lesp/service-config/nginx.conf, stacks/lesp/setup.sh, stacks/uwsgi/setup.sh, vagrant-spk
I absolutely still need to test/validate this PR. :) But it addresses #250 in theory. I believe we can safely replace packages like php-fpm7.3 with php-fpm, as the latter depends on the former and we want to use the default version a given Debian release uses. Ideally, I need to figure out how to avoid so many version-specific references so switching boxes is not painful.
=> Update base box to Debian Buster

vagrant-spk
Fixes #247 
After making this change, on Ubuntu 20.04, I was able to complete a standard test of the php-app-to-package-for-sandstorm without issue. It probably would be good to test more of the various functions, but at minimum, this is basically useful without an unsupported version of Python, which we need to get away from.
=> Switch to Python 3

release.sh
In review of #262, @zenhack suggested pulling this information from vagrant-spk rather than confirming it is the same in both places. This change to the script is tested (as a stub in a separate script file) to correctly do that. I flipped the order the variables are populated, because TAG_NAME is closer to the output of the vagrant-spk --version command. I attempted to figure out how to get TAG_NAME to populate in one line, but was unsuccessful, because I am a bash rookie. (Maybe I can argue it's more readable as two lines anyways...)
=> Release script pulls version from vagrant-spk

stacks/lemp/launcher.sh, stacks/lesp/launcher.sh, stacks/uwsgi/launcher.sh
This is one of the tweaks I particularly liked in @zenhack's TTRSS port, that I think we should bring into the default vagrant-spk stack design where applicable.
(I'd also like to probably bring in the touch db-created logic for the lemp stack in a future PR, though I may comment it out by default, since not all lemp stack projects will need a prepopulated SQL database.)
=> Implement wait_for in launcher.sh

release.sh
This is definitely a draft, I haven't tested it, but made this based on https://cli.github.com/manual/gh_release_create and what's already in this script. #256 documents many other pain points I had running the release script before.
`gh` recently added the ability to create releases, and it's *fairly similar* to github-release. It looks like it supports the GITHUB_TOKEN method of authentication too, so I left that part of the script alone.
The only thing I am aware of that this won't do correctly, is rename the EXE file uploaded to include the tag name, as seen in the artifacts here: https://github.com/sandstorm-io/vagrant-spk/releases because the gh release script doesn't appear to have any support for setting a filename separate from the actual file you upload from a glance. The …
=> First draft of switching to gh tool

release.sh
I am testing a GitHub Action in another branch, and there is no programmatic way to skip the changelog check, which I want to do for dry run tests prior to merging the action. I copied this from the option to skip the git clean check.
=> Add env variable to skip changelog check

release.sh
So yesterday I introduced a slight regression in the cleanliness of the release script, in that renaming the file for release upload also moved it out of it's folder, which is gitignored and such. This should fix that.
=> Keep Windows EXE in its folder

stacks/golang/setup.sh
1.16.6 includes some security fixes, though I don't think
any of them are likely to affect Sandstorm apps.
=> Bump golang toolchain version.

vagrant-spk
Apparently I am the first person to run vagrant-spk upgradevm since the
Python 3 update. Without this, write() throws an exception complaining
that we passed it a str instead of bytes.
=> Add missing .encode("UTF-8") calls.

vagrant-spk
The box itself was updated to buster a while back, but I noticed that
the comment still says stretch. I also got rid of the vboxfs bit; IIRC
there were separate images for these at one time, but they are no longer
needed.
=> Update bitrotten comment in Vagrantfile template.

vagrant-spk
This is approaching bikeshedding, but I did want to get rid of the "Sandstorm snapshot of" bit...
I wanted to express here that Debian boxes should generally work with vagrant-spk if they have vboxsf support, which is not presently a guarantee depending which Debian box you go with (considering we're still targeting buster at the moment). The example text though should also help briefly express that as of bullseye, contrib- is no longer required.
=> Update bitrotten box comment

vagrant-spk
This is a really trivial thing, but: my terminal's link detection seems
to want to include the period after the url in the url itself, which
means just trying to right click & open the link does not work
correctly. This patch gets around this by formatting the text in a way
that doesn't have the period at the end. I believe it still scans ok.
=> Minor formatting tweak in Vagrantfile message

stacks/lemp/setup.sh, stacks/uwsgi/setup.sh
Fixes #321. It looks like Oracle has rotated their GPG keys starting with 8.0.28 (and likely patch releases for older supported versions). A note specifies the change in keys and their fingerprints here: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup
I checked and the key at the new URL matches the KeyID described in the issue.
=> Update MySQL repo GPG key

vagrant-spk
Adding the automount option fixes a dependency cycle that can cause
Sandstorm to fail to start on boot for some development VMs.
The `host\x2ddot\x2dsandstorm.mount` is wanted by the `remote-fs.target`,
however it needs the `virtualbox-guest-utils.service` to mount
successfully.  The `virtualbox-guest-utils.service` can be made to run
before `remote-fs.target`, but I have never managed to make it be ready
for mounting Virtualbox Synced Folders at boot time.  It complains of
shared memory errors.  All of this causes the `remote-fs.target` to fail,
which causes `sandstorm.service` to fail to start at boot time.
This solution enables the automount option.  `/host-dot-sandstorm` is
instead no longer required for completion of the `remote-fs.target` and is
mounted on demand for `vagrant-spk`. …
=> Fix remote-fs.target dependency cycle

stacks/lemp/launcher.sh, stacks/lemp/service-config/nginx.conf, stacks/lemp/setup.sh, stacks/lesp/launcher.sh, stacks/lesp/service-config/nginx.conf, stacks/lesp/setup.sh, stacks/node/setup.sh, stacks/uwsgi/build.sh, stacks/uwsgi/launcher.sh, stacks/uwsgi/setup.sh, vagrant-spk
I think we need to address #330 before we merge this, and I also am going to do some testing against our test packages yet. We still need good test packages for some stacks (#298), which is also arguably blocking #290.
This also fixes #255. Node 14 is a supported LTS releae, and node-capnp supports Node 14, so we'll bump that up to be relatively modern as well.
=> Upgrade base box to Bullseye

stacks/lemp/setup.sh, stacks/uwsgi/setup.sh, vagrant-spk
I believe this should fix #337, we already install it in two common stacks anyways, and presumably it used to be installed in previous boxes.
=> Install GnuPG in global-setup

stacks/golang/setup.sh
This includes a few security fixes in the stdlib.
=> Bump golang toolchain version

stacks/golang/setup.sh
This change should end the need for regular updates to the Go stack: We will grab the latest version of Go, and store the version with the .sandstorm folder so we grab the same one on successive builds.
Note that I didn't change (or bother to check what it was) the working directory, and ended up using absolute paths, and I couldn't run "go" from PATH on line 22, so I continued that behavior. Ian, if you can make this PR more succinct or better, I am good with that, but this seems to work.
(Note, I am about to force-push to fix a tabs vs. spaces crime.)
=> Use the latest golang when building a new package

stacks/lemp/launcher.sh, stacks/lesp/launcher.sh, stacks/static/launcher.sh, stacks/uwsgi/launcher.sh
I added this bit to the launcher script for every stack that bothers to create /var/log (basically, any which include Nginx and/or MySQL). It's possible other stacks would benefit from it, but I didn't want to add unnecessary script to any stacks which don't definitively include behavior logging there.
=> Rotate log files by default

vagrant-spk
This has been a constant point for me where the VM has hung completely or taken 30+ minutes to complete since using Virtualbox 7.x with Bookworm. This week's updates to the latest Bookworm box and Virtualbox revision did not help. The Debian box uses Guest Additions 6.x, and it appears to work fine with 7.x anyways, so I want to just disable this plugin.
=> Skip upgrading Guest Additions

stacks/node/setup.sh
Using the old curl | bash setup scripts now creates a 60-second delay where it complains and tells you to stop using it. This is the new style, which I used to package WBO. I used Node 18 for WBO, but selected Node 20 here, because it will be the current LTS in less than a week at this point, and I want to future-proof this PR for a release I intend to create... soon?
=> Replace Node install

stacks/meteor/setup.sh
I haven't tested this, but on manual review, this looks like the only places this would need to be updated? I did check that the Cloudfront URL was still accurate for the Meteor download and such as well. Presumably we should have meteor-spk updated to 2.x at some point and then update this again.
=> Use latest meteor-spk in Meteor stack

stacks/lemp/launcher.sh, stacks/uwsgi/launcher.sh
So I believe this change is necessary to stabilize our lemp and uwsgi stacks, and fixes the roadblock I've been fighting on my own package. MySQL's documentation states --initialize should exit without changes if the directory isn't empty (aka, already initialized), but my guess is because we launch initialize without a password (or skip-grant-tables like our main process launch), it encounters an access error trying to verify the initialization is already done. I think the best choice is to just only initialize a grain once, it avoids some log cruft and is (probably) more efficient.
https://dev.mysql.com/doc/refman/8.0/en/data-directory-initialization.html#data-directory-initialization-procedure
I am also taking a behavior Ian used effectively in his grains and introducing it as a …
=> Initalize MySQL Once

stacks/golang/setup.sh
So our Go stack was broken, and I figured out why: https://go.dev/VERSION?m=text used to return the latest Go version (technically, the version the Go website uses, but I digress). Now it also includes a timestamp, and that broke this script.
=> Go: Get latest version correctly
