- README.md
- vagrant-spk
Solves https://github.com/zarvox/vagrant-spk/issues/6
> Solves /opt/app.sandstorm/

- vagrant-spk
@paulproteus Feel free to reword anything you like here.  When you're satisfied, click the merge button.
Closes #10.
> Add "diy" stack, which has noops for each of the three scripts

- vagrant-spk
> Add more comments about vagrant-vbguest

- stacks/meteor/launcher.sh
- stacks/meteor/setup.sh
This is dependent on https://github.com/sandstorm-io/meteor-spk/pull/10 and a new release of meteor-spk being pushed. (0.1.5 is the current release)
> use meteor-spk's start.js

- vagrant-spk
Some more useful text for `--help`.  Aims to close issue #53 .  FWIW I see that `--wipe` was removed in 4ef5a210a7ee2a42b4a8b0abd8924f7d037e5def  (thanks :) )
> More useful --help text.  Ref issue #53

- stacks/meteor/setup.sh
- vagrant-spk
Hi @zarvox,
I think I'm going to self-merge this because I have manually tested it, and it works OK for Meteor apps, and I have a goal of making sure the hackathon people tomorrow have the best experience possible.
If you're +1 on these changes I can make them to other stacks, too, and/or you can if you prefer to for some reason.
Semi-apologies for the self-merge.
> Quieter output for meteor stack

- vagrant-spk
This only affects "feature-flagged" (experimental) code, so I'm going to self-merge. I don't claim the quality of this is super high, but comments welcome.
> In vagrant-spk auto meteor, add git repo name to generated package

- vagrant-spk
> Append not clobber

- vagrant-spk
This helps Meteor apps fully load when packaged and run on HTTPS
Sandstorm servers.
> vagrant-spk auto: Automatically upgrade HTTP Google Fonts to HTTPS

- CHANGELOG.md
> Add v0.130 details to CHANGELOG.md

- vagrant-spk
@zarvox please review/merge soon, and once this is in, I will cut a release and write release notes.
Please read the strings carefully; I'm happy to take feedback on them, but I am hoping to get this done soon so I want as low-latency and high-confidence a review as possible. I'm willing to make string changes now; less excited about doing so as time moves forward.
> If the base box depends on debian/jessie64, say how to proceed

- release.sh
I'm going to self-merge this, but am willing to take review if people have review feedback!
> Improve release script

- release.sh
Going to self-merge this, but happy to take feedback.
> Stop using undefined variables in release.sh

- stacks/diy/setup.sh
> diy stack: nudge to run apt-get update before installing things

- stacks/lesp/build.sh
- stacks/lesp/launcher.sh
- stacks/lesp/setup.sh
This commit takes the LEMP stack (Linux, NginX, MySQL, PHP), and replaces the MySQL part with SQLite, which should make those stacks which don't require a full MySQL produce a smaller app image.
> Added "LESP" stack

- vagrant-spk
Close #118
Requesting your review/merge, @zarvox
> Add reload command

- vagrant-spk
Close #132
Testing done:
- Asked @synchrone to manually verify on a Linux system: success.
- Asked @phildini to manually verify on a Mac system: success.
> Use PCNet-Fast III by default

- vagrant-spk
> Configure apt to retry downloads that fail

- vagrant-spk
@zarvox , a possible follow-up to your #141
> exit(1) when specifying no stack

- HOWTO-libvirt.md
Thanks to @zarvox for mentioning the right package.
> Refine libvirt HOWTO for Debian

- CHANGELOG.md
Adding changelog; going to self-merge so I can do a release.
> Add Changelog for v0.159

- .gitignore
Hey @zarvox I'm going to self-merge this but if you object, we can revert/discuss/document the rationale.
> Add Emacs gunk to .gitignore

- vagrant-spk
There were a few problems. They're detailed in these commits. I'm going to self-merge and do a release, since the status quo is broken.
> Fix enter-grain, which was broken in all builds

- vagrant-spk
For your review + merge @zarvox.
Context: This is based on conversation with @dwrensha at https://github.com/jparyani/sandstorm-test-app/pull/2/files/2ef3c59702eb1ca7a6c4de314e988432544f1cfe#r66181184 and a conversation with Drew in person.
> Add comments about synced_folders

- README.md
We edit the docs.sandstorm.io content more often than this README.
@zarvox I'm going to go ahead and merge this now, but if you have feedback I'd be grateful to hear it.
> Adjust README.md to link to docs

- stacks/lemp/setup.sh
This change adds secure-file-priv to my.conf during setup.sh. For details see: https://github.com/sandstorm-io/vagrant-spk/issues/195
> Add secure-file-priv to my.conf

- vagrant-spk
added a solution as described here:
https://github.com/hashicorp/vagrant/issues/9442
> temp fix for broken vagrant box link

- vagrant-spk
> Update sources before installing curl

- stacks/golang/setup.sh
Misc. bugfix release from a few days ago.
> golang stack: Bump version of the toolchain

- stacks/golang/setup.sh
Bugfix release from a few days ago
> golang stack: bump toolchain version

- stacks/golang/setup.sh
> golang stack: Bump golang toolchain version.

- stacks/golang/setup.sh
Yes, they really put out two releases one day apart...
> Bump golang toolchain version.

- stacks/golang/setup.sh
> Update golang to 1.17

- stacks/golang/setup.sh
> Bump golang toolchain version

- stacks/lemp/launcher.sh
- stacks/lemp/service-config/nginx.conf
- stacks/lemp/setup.sh
- stacks/lesp/launcher.sh
- stacks/lesp/service-config/nginx.conf
- stacks/lesp/setup.sh
- stacks/uwsgi/build.sh
- stacks/uwsgi/setup.sh
- vagrant-spk
Fixes #343 
This is not tested/validated yet, but "should work".
> Change base box to Bookworm
